// <auto-generated />
namespace KeesingTechnologies.Assignment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialmigrationcreatedatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialmigrationcreatedatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201605081315401_Initial migration, create database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
